### ISSUE TITLE
CPUs not bursting in flames!

### ISSUE THREAD

**Issue by tomasj** [BusinessDuck/async-genetic#5]
**TL;DR**
Framework doesn't seem to utilize all CPU cores available on the machine. Is there any way to adjust this? (eg. set thread count somewhere)
**Detais**
I've implemented relative simple GA, with the fitness being the most complex and computationaly intensive code (as it should probably :). As the fitness grown bigger the algo went hell a lot slower. Said OK, let's run it on a decent machine. But even on high end CPU with 32 virtual cores it got only utilized by avg 6%. That's roughly 2 logical cores out of 32. On my lap on another hand it used 5 out of 8 logical cores on avg.

**Comment by BusinessDuck** [comment]
Hi @tomasj, `async-genetic` is single thread. But! You have `async` scoring function. You should implement `workers` in you side. For example, scoring calculations takes a lot of CPU time, split it to different workers and merge when all data is ready and then pass to `async-genetic` as Promised value. It's pretty works for me :)

**Comment by louisjmorgan** [comment]
Could you give a code example of this please?

**Comment by BusinessDuck** [comment]
https://nodejs.org/api/worker_threads.html

```javascript
import {
  Worker, isMainThread, parentPort, workerData,
} from 'node:worker_threads';

if (isMainThread) {
  module.exports = function parseJSAsync(script) {
    return new Promise((resolve, reject) => {
      const worker = new Worker(__filename, {
        workerData: script,
      });
      worker.on('message', resolve);
      worker.on('error', reject);
      worker.on('exit', (code) => {
        if (code !== 0)
          reject(new Error(`Worker stopped with exit code ${code}`));
      });
    });
  };
} else {
  const { parse } = require('some-js-parsing-library');
  const script = workerData;
  parentPort.postMessage(parse(script));
}
```

**Comment by BusinessDuck** [comment]
Check the worker threads API, in main thread create worker and subscribe to messages. else (mean worker thread) await for incoming messages and run scoring for anything. Pass data to scoring worker via message (stringify json)

**Comment by louisjmorgan** [comment]
Thanks for the quick response. I ended up using threads.js which works with node or in the browser using the same code. I'll show a basic implementation in case anyone else comes across this thread.

outside of fitness function:
`
import { spawn, Pool, Worker } from 'threads';
const pool = Pool(async () => spawn(new Worker(new URL('./workers/fitnessWorker.js', import.meta.url))), 8);
`
Inside fitness function:
`
const task = pool.queue((fitnessWorker) => fitnessWorker.calculate(testReq)); //return a promise from the worker
const result = await task;
return {fitness: result}
`
